# Generated by Django 3.1.4 on 2020-12-14 07:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_software_project_backend_side', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BluetoothToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BDaddress', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name='floor',
            name='id',
        ),
        migrations.AddField(
            model_name='floor',
            name='floor_number',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
