# Generated by Django 3.1.4 on 2020-12-14 08:23

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_software_project_backend_side', '0002_auto_20201214_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='BluetoothModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Device_name', models.TextField()),
                ('Location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('Floor', models.IntegerField(default=1)),
                ('Room', models.IntegerField(default=7011)),
                ('X_Coordinate', models.FloatField()),
                ('Y_Coordinate', models.FloatField()),
            ],
        ),
    ]
