# Generated by Django 3.1.4 on 2020-12-14 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_software_project_backend_side', '0003_bluetoothmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluetoothmodel',
            name='Date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
