# Generated by Django 3.1.4 on 2020-12-14 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('senior_software_project_backend_side', '0004_auto_20201214_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluetoothmodel',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bluetoothmodel',
            name='Device_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bluetoothmodel',
            name='X_Coordinate',
            field=models.FloatField(default=1.234),
        ),
        migrations.AlterField(
            model_name='bluetoothmodel',
            name='Y_Coordinate',
            field=models.FloatField(default=5.678),
        ),
    ]
