# Generated by Django 3.1.4 on 2020-12-17 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_software_project_backend_side', '0005_auto_20201214_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bluetoothmodel',
            old_name='Location',
            new_name='Latitude_Longtitude',
        ),
        migrations.AddField(
            model_name='bluetoothmodel',
            name='Location_Building',
            field=models.TextField(default='ECC Building'),
        ),
        migrations.AlterField(
            model_name='bluetoothmodel',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 12, 20, 50, 383250)),
        ),
    ]
