# Generated by Django 3.1.4 on 2020-12-17 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_software_project_backend_side', '0006_auto_20201217_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bluetoothmodel',
            old_name='Location_Building',
            new_name='Location',
        ),
        migrations.AlterField(
            model_name='bluetoothmodel',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 12, 27, 24, 862833)),
        ),
    ]
